name: network
description: GreenLoop API client — central networking layer using Dio.
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  dio_cache_interceptor: ^3.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.14
