name: auth
description: GreenLoop auth package managing email/password login and session state.
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  network: ^1.0.0
  data_models: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.14
