name: widget_catalog
description: A catalog app to preview GreenLeaf UI components.
publish_to: 'none'
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  ui_kit: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
